---
  - hosts: kubservers

# Tasks Section
    tasks:
     - name: Copy deploy file into Kubernetes Server
       copy:
         src: /home/ec2-user/simpleapp-deploy-k8s.yaml
         dest: /home/ec2-user/simpleapp-deploy-k8s.yaml
         owner: ec2-user
         group: ec2-user
         mode: '744'

     - name: Deploy simpleapp in kubernets
       command: kubectl apply -f simpleapp-deploy-k8s.yaml
